# Generated by Django 3.0.7 on 2020-06-26 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('klass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('Time_starts', models.DateTimeField(auto_now_add=True)),
                ('Time_expires', models.DateTimeField()),
                ('dars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klass.Dars')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('number', models.IntegerField(default=1)),
                ('question', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions')),
                ('caution_help', models.CharField(max_length=500)),
                ('Barem', models.IntegerField()),
                ('Time_considered_to_solve_in_minute', models.IntegerField(default=1)),
                ('choiceOne', models.CharField(blank=True, max_length=500, null=True)),
                ('choiceTwo', models.CharField(blank=True, max_length=500, null=True)),
                ('choiceThree', models.CharField(blank=True, max_length=500, null=True)),
                ('choiceFour', models.CharField(blank=True, max_length=500, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Exam')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(upload_to='Answers')),
                ('selected_Choice', models.CharField(blank=True, max_length=500, null=True)),
                ('Is_seened', models.BooleanField(default=False)),
                ('Is_Solved', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klass.Student')),
            ],
            options={
                'ordering': ('question__number',),
            },
        ),
    ]
