# Generated by Django 3.0.5 on 2020-07-30 08:42

from django.db import migrations, models
import django.db.models.deletion
import exam.models
import school_home.views


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('klass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('time_starts', models.DateTimeField()),
                ('time_ends', models.DateTimeField()),
                ('dars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klass.Dars')),
            ],
            options={
                'verbose_name_plural': 'امتحانات',
                'ordering': ('-time_starts',),
            },
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/tashrihi')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Exam')),
            ],
            options={
                'verbose_name_plural': 'سوالات تشریحی',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/test')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('choice_one', models.CharField(blank=True, max_length=150, null=True)),
                ('choice_two', models.CharField(blank=True, max_length=150, null=True)),
                ('choice_three', models.CharField(blank=True, max_length=150, null=True)),
                ('choice_four', models.CharField(blank=True, max_length=150, null=True)),
                ('correct_ans', models.IntegerField(validators=[exam.models.validate_ans])),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Exam')),
            ],
            options={
                'verbose_name_plural': ' سوالات تستی',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Answer_WQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(upload_to='answers', validators=[school_home.views.file_size])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klass.Student')),
            ],
            options={
                'verbose_name_plural': 'پاسخ سوالات تشریحی',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_choice', models.IntegerField(validators=[exam.models.validate_ans])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klass.Student')),
            ],
            options={
                'verbose_name_plural': 'پاسخ سوال های تستی',
            },
        ),
    ]
