# Generated by Django 3.0.7 on 2020-06-08 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0001_initial'),
        ('klass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='dars',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klass.Dars'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klass.Student'),
        ),
    ]
