# Generated by Django 3.0.7 on 2020-06-30 17:11

from django.db import migrations, models
import school_home.views


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20200626_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.ImageField(upload_to='answers', validators=[school_home.views.file_size]),
        ),
    ]
