# Generated by Django 3.0.7 on 2020-07-01 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20200630_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='dars',
        ),
        migrations.RemoveField(
            model_name='question',
            name='exam',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
