# Generated by Django 3.0.8 on 2020-07-12 18:16

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20200712_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='JD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', django_jalali.db.models.jDateField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
