# Generated by Django 3.0.8 on 2020-07-12 18:50

import django.core.validators
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_jd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jd',
            name='time',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ تحویل'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_ans',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
