# Generated by Django 3.0.8 on 2020-07-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_auto_20200713_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('question__number',), 'verbose_name_plural': 'پاسخ ها'},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name_plural': 'امتحانات'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('number',), 'verbose_name_plural': 'سوالات'},
        ),
        migrations.AlterModelOptions(
            name='wquestion',
            options={'ordering': ('number',), 'verbose_name_plural': 'سوالات تشریحی'},
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='Is_Solved',
            new_name='is_solved',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='selected_Choice',
            new_name='selected_choice',
        ),
        migrations.AlterField(
            model_name='exam',
            name='time_starts',
            field=models.DateTimeField(),
        ),
    ]
