# Generated by Django 3.0.8 on 2020-07-13 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_auto_20200713_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='Is_seened',
            new_name='is_seened',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='choiceFour',
            new_name='choice_four',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='choiceOne',
            new_name='choice_one',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='choiceThree',
            new_name='choice_three',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='choiceTwo',
            new_name='choice_two',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Time_considered_to_solve_in_seconds',
            new_name='time_considered_to_solve_in_seconds',
        ),
    ]
