# Generated by Django 3.0.7 on 2020-06-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('explanation', models.CharField(max_length=500)),
                ('time', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='news')),
            ],
            options={
                'ordering': ('-time',),
            },
        ),
    ]
