# Generated by Django 3.0.7 on 2020-06-30 17:11

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news', validators=[news.models.news_image_size]),
        ),
    ]
