# Generated by Django 3.0.7 on 2020-07-01 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200630_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-time',), 'verbose_name_plural': 'اخبار مدرسه'},
        ),
    ]
