# Generated by Django 3.0.8 on 2020-07-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200716_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameImage', models.CharField(max_length=140, null=True)),
                ('uploadedImage', models.ImageField(null=True, upload_to='Upload/')),
            ],
        ),
    ]
