# Generated by Django 3.0.5 on 2020-07-30 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('passwd', models.CharField(max_length=20, unique=True)),
                ('Time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'دروس',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='teachers')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'معلمان',
            },
        ),
        migrations.CreateModel(
            name='Tamrin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to='tamrin/None')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_expire', models.DateTimeField()),
                ('dars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klass.Dars')),
            ],
            options={
                'verbose_name_plural': 'تمارین   ',
                'ordering': ('-time_expire',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='students')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'دانش آموزان',
            },
        ),
        migrations.CreateModel(
            name='File_teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to='klass/Files_teacher')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('dars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klass.Dars')),
            ],
            options={
                'ordering': ('-time',),
            },
        ),
        migrations.AddField(
            model_name='dars',
            name='students',
            field=models.ManyToManyField(to='klass.Student'),
        ),
        migrations.AddField(
            model_name='dars',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klass.Teacher'),
        ),
    ]
