# Generated by Django 3.0.7 on 2020-06-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('klass', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
    ]
