# Generated by Django 3.0.7 on 2020-06-26 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klass', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new',
        ),
    ]
