# Generated by Django 3.0.7 on 2020-06-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klass', '0002_delete_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='dars',
            name='passwd',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
