# Generated by Django 3.0.7 on 2020-07-01 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20200701_1007'),
        ('klass', '0003_dars_passwd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'دانش آموزان'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': 'معلمان'},
        ),
        migrations.DeleteModel(
            name='Dars',
        ),
    ]
