# Generated by Django 3.0.7 on 2020-07-01 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klass', '0004_auto_20200701_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('passwd', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='Classes')),
                ('Time_created', models.DateTimeField(auto_now_add=True)),
                ('students', models.ManyToManyField(to='klass.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klass.Teacher')),
            ],
            options={
                'verbose_name_plural': 'دروس',
            },
        ),
    ]
