# Generated by Django 3.0.7 on 2020-07-01 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klass', '0005_dars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tamrin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to='tamrin/None')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_expire', models.DateTimeField()),
                ('dars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klass.Dars')),
            ],
            options={
                'ordering': ('time_created',),
            },
        ),
    ]
