# Generated by Django 3.0.7 on 2020-07-06 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klass', '0006_tamrin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tamrin',
            options={'ordering': ('time_created',), 'verbose_name_plural': 'تمارین   '},
        ),
    ]
