# Generated by Django 3.0.8 on 2020-07-23 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klass', '0007_auto_20200706_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dars',
            name='image',
        ),
    ]
