# Generated by Django 3.0.8 on 2020-07-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klass', '0008_remove_dars_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tamrin',
            options={'ordering': ('-time_expire',), 'verbose_name_plural': 'تمارین   '},
        ),
    ]
