# Generated by Django 3.0.5 on 2020-07-27 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klass', '0009_auto_20200724_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to='klass/Files_teacher')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('dars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klass.Dars')),
            ],
            options={
                'ordering': ('-time',),
            },
        ),
    ]
