# Generated by Django 3.0.7 on 2020-06-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('Time_Posted', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(upload_to='gallery/images')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('Time_Posted', models.DateTimeField(auto_now_add=True)),
                ('video', models.FileField(upload_to='gallery/videos')),
            ],
        ),
    ]
