# Generated by Django 3.0.8 on 2020-07-24 18:46

from django.db import migrations, models
import django.db.models.deletion
import my_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('klass', '0009_auto_20200724_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_of_Tamrin_for_every_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='Tmarin/Answers', validators=[my_profile.models.file_size])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klass.Student')),
                ('tamrin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klass.Tamrin')),
            ],
        ),
    ]
