# Generated by Django 3.0.5 on 2020-07-25 15:39

from django.db import migrations, models
import my_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_of_tamrin_for_every_student',
            name='file',
            field=models.FileField(upload_to='Tamrin/Answers', validators=[my_profile.models.file_size]),
        ),
    ]
