# Generated by Django 3.0.5 on 2020-07-27 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0002_auto_20200725_2009'),
        ('my_profile', '0002_auto_20200725_1523'),
    ]

    operations = [
    ]
